@startuml
'https://plantuml.com/sequence-diagram
participant 立项
participant 审批中心
queue 审批中心mq
control 审批状态映射
participant oa审批
queue oa的回调

立项 -> 审批中心 : 立项申请 or 添加预算
审批中心 -> oa审批 : 发起审批请求
activate oa审批
oa审批 -> oa审批 : 开始执行审批流程
oa审批 -> oa的回调 : 各个节点审批状态处理
deactivate oa审批
oa的回调 --> 审批中心 : 状态回传
审批中心 -> 审批状态映射 : 根据业务注册的状态和oa审批的状态进行映射
审批状态映射 --> 审批中心 : 传递状态变更实体
审批中心 -> 审批中心mq : 根据注册好的业务标识发送消息
审批中心mq -->o 立项 : 立项成功

group 撤销项目
    立项 -> 审批中心 : 撤销项目
    审批中心 -> oa审批 : 撤销审批流程
    审批中心 -> 审批中心 : 记录项目审批状态为中止
end

group 修改重审
    oa审批 -> oa审批 : 审批被驳回
    oa审批 -> 审批中心 : 审批状态变更为驳回
    审批中心 -> 审批中心mq : 通知下游去修改项目状态
    立项 -> 审批中心 : 修改信息后重新提交审核
    审批中心 -> oa审批 : 重新执行被驳回的审批节点
end



@enduml