@startuml

participant 立项
participant 科目和资源包
participant 资源包扣减记录
participant 资源发放

group 立项申请资源预算 or 追加预算

    立项 -> 科目和资源包 : 预算申请
    activate 科目和资源包
    科目和资源包 -> 科目和资源包 : 关联项目和预算申请的批次生成特定的业务标识，用于后期的资金链路回溯和对账
    科目和资源包 -> 科目和资源包 : 根据科目的资源包限制来验证扣减
    科目和资源包 -> 科目和资源包 : 扣减特定的科目资源包
    科目和资源包 -> 资源包扣减记录 : 记录扣减详情
    deactivate 科目和资源包

end

group 项目审批失败

    立项 -> 科目和资源包 : 立项审批失败
    activate 科目和资源包
    科目和资源包 -> 科目和资源包 : 回退之前业务标识过的扣减金额，释放锁定的金额
    科目和资源包 -> 资源包扣减记录 : 记录回退详情
    deactivate 科目和资源包

end

group 资源发放就位，流转至不能回退的状态
    资源发放 -> 科目和资源包 : 确认资源发放
    activate 科目和资源包
    科目和资源包 -> 科目和资源包 : 更新发放的状态，将锁定的金额状态变为核销
    科目和资源包 -> 资源包扣减记录 : 记录发放更新为终态
    deactivate 科目和资源包

end

group 资源发放中心 预算释放
    资源发放 -> 科目和资源包 : 资源回退或者部分回退
    activate 科目和资源包
    科目和资源包 -> 科目和资源包 : 更新状态，为回退的资金进行操作
    科目和资源包 -> 资源包扣减记录 : 记录回退的金额
    deactivate 科目和资源包

end

@enduml