@startuml

actor 审批人
participant 资源申请模块
participant 审批中心模块
participant flow流程中心


group 获取列表信息
    审批人 -> 资源申请模块: 查看审批已审和代办列表
    资源申请模块 -> flow流程中心: 根据当前用户筛选出对应的流程id和任务id
    资源申请模块 -> 审批人: 返回数据结果，其中包含流程id和任务id
end

group 审批通过/驳回
    审批人 -> 资源申请模块: 根据流程id和任务id来进行审批
    资源申请模块 -> flow流程中心: 调用oa的能力进行审批
    资源申请模块 -> 审批人: 返回审批结果
    flow流程中心 --> 审批中心模块: 同步oa详情页上操作的结果
    审批中心模块 --> 资源申请模块: 计算当前资源申请的状态
    资源申请模块 --> 审批人: 时时展示状态
end

group 数据导出
    审批人 -> 资源申请模块: 查看审批已审和代办列表
    资源申请模块 -> flow流程中心: 根据当前用户筛选出对应的流程id和任务id
    资源申请模块 -> 审批人: 返回数据结果，其中包含流程id和任务id
end


@enduml
