@startuml
'https://plantuml.com/sequence-diagram
participant 资源中心
participant 审批中心
control 审批状态映射
queue 审批中心mq
participant oa审批
queue oa审批回调
participant 配置平台
participant 配置平台审批

资源中心 -> 审批中心 : 申请资源排期和资源物料
group 资源排期
    资源中心 -> 审批中心 : 申请资源排期 or 追加排期
    activate oa审批
    审批中心 -> oa审批 : 开始审流程
    oa审批 -> oa审批 : 审批节点流转
    oa审批 -> oa审批回调 : 向下游通知审批的流转状态
    deactivate oa审批
    oa审批回调 --> 审批中心 : 返回每个节点的审批状态
    审批中心 -> 审批状态映射 : 映射到资源排期的状态
    审批状态映射 -> 审批中心 : 返回正确的资源排期时间的状态实体
    审批中心 -> 审批中心mq : 发送资源排期的状态变更消息
    审批中心mq -> 资源中心 : 资源排期状态变更

end

资源中心 -> 审批中心 : 资源排期公布
审批中心 -> oa审批: 程序控制通过 资源排期 节点，并流转下一个节点

group 物料排期
    资源中心 -> 配置平台 : 进行物料配置

    group 三方配置平台审核和oa审核流程接入
        配置平台 -> 配置平台审批 : 开始进行第三方审批
        activate 审批中心
        配置平台审批 -> 审批中心 : 读取审批流的节点，如果到达物料审批环节，则开始流转oa审批流
        审批中心 -> oa审批 : 继续oa审批流程
        配置平台审批 -> 配置平台审批 : 第三方审批节点流转
        配置平台审批 -> 审批中心 : 告知节点流转状态
        审批中心 -> 审批中心 : 更新节点状态
        审批中心 -> oa审批 : 操作通过或者驳回审批状态
        deactivate 审批中心

    end
    group 在物料审批没有全部通过前 追加排期
        资源中心 -> 资源中心 : 追加排期
        资源中心 -> 审批中心 : 追加排期申请审批
        审批中心 -> 资源中心 : 审批状态通知
        资源中心 -> 资源中心 : 根据所有的排期审批流程和物料审批流程统筹出一个资源申请的状态
    end
end

group 追加排期
    资源中心 -> 资源中心 : 如果是物料审批通过后，追加排期,不走审批
end


@enduml